// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2u57qqIyizw7NcH6f1Y8V0JdiZOcGPCI',
    appId: '1:8673329015:web:2eb452f1fc98bd9b436b72',
    messagingSenderId: '8673329015',
    projectId: 'grocery-helper-e7d24',
    authDomain: 'grocery-helper-e7d24.firebaseapp.com',
    databaseURL: 'https://grocery-helper-e7d24-default-rtdb.firebaseio.com',
    storageBucket: 'grocery-helper-e7d24.appspot.com',
    measurementId: 'G-9SQNHERK4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiKotM2szdejxSw19AAVAjq4KE5XWWSq4',
    appId: '1:8673329015:android:358e9f51c8856677436b72',
    messagingSenderId: '8673329015',
    projectId: 'grocery-helper-e7d24',
    databaseURL: 'https://grocery-helper-e7d24-default-rtdb.firebaseio.com',
    storageBucket: 'grocery-helper-e7d24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBj8HkKEA8wFc2bBZsH5SCi1KNQW0n5Io',
    appId: '1:8673329015:ios:6b4ec6beff18648c436b72',
    messagingSenderId: '8673329015',
    projectId: 'grocery-helper-e7d24',
    databaseURL: 'https://grocery-helper-e7d24-default-rtdb.firebaseio.com',
    storageBucket: 'grocery-helper-e7d24.appspot.com',
    iosBundleId: 'com.example.groceryHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBj8HkKEA8wFc2bBZsH5SCi1KNQW0n5Io',
    appId: '1:8673329015:ios:7e10ee0bac60b408436b72',
    messagingSenderId: '8673329015',
    projectId: 'grocery-helper-e7d24',
    databaseURL: 'https://grocery-helper-e7d24-default-rtdb.firebaseio.com',
    storageBucket: 'grocery-helper-e7d24.appspot.com',
    iosBundleId: 'com.example.groceryHelper.RunnerTests',
  );
}
