name: grocery_helper
description: Simplifies your life

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter_native_splash:  ^2.3.13
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

flutter_native_splash:
  image:  assets/grocery_logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/grocery_logo.png
