name: grocery_helper
description: Simplifies your life

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  intl: ^0.18.1
  flutter_timeline_calendar: ^1.0.9
  flutter_launcher_icons: ^0.13.1


  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.2.1
  cached_network_image: ^3.3.1
  firebase_core: ^2.27.1
  firebase_performance: ^0.9.3+18
  firebase_auth: ^4.17.9
  google_sign_in: ^6.2.1
  firebase_ui_auth: ^1.13.1
  firebase_ui_oauth_google: ^1.3.1

flutter_native_splash:
  image:  assets/grocery_logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  #Use following command to regenerate app icons
  #flutter pub run flutter_launcher_icons -f flutter_launcher_icons.yaml
  image_path: "assets/grocery_logo.png"
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/grocery_logo.png
